name: PARTH WORKFLOW 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create file.txt
        run: |
          echo "Hello World" > file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-file
          path: file.txt